### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/nextjs-starter#80]
Broken since #77 (sorry). I'll fix it when I can see the issue on Vercel.

**Comment by sboerrigter** [comment]
Here it is 😇:

```
12:56:20.334  	Cloning github.com/trendwerk/nextjs-starter (Branch: blog-filter, Commit: 890dd98)
12:56:20.899  	Cloning completed in 565ms
12:56:20.900  	Analyzing source code...
12:56:22.271  	Installing build runtime...
12:56:22.715  	Build runtime installed: 443.594ms
12:56:23.157  	Looking up build cache...
12:56:23.197  	Build cache not found
12:56:23.645  	Installing dependencies...
12:56:34.818  	> @ampproject/toolbox-optimizer@2.6.0 postinstall /vercel/3a408542/node_modules/@ampproject/toolbox-optimizer
12:56:34.818  	> node lib/warmup.js
12:56:35.214  	[7mAMP OPTIMIZER[0m Downloaded latest AMP runtime data.
12:56:35.660  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/webpack/node_modules/fsevents):
12:56:35.660  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:56:35.660  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
12:56:35.660  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:56:35.663  	added 904 packages from 396 contributors in 11.624s
12:56:36.019  	25 packages are looking for funding
12:56:36.019  	  run `npm fund` for details
12:56:36.232  	Running "next build"
12:56:36.809  	info  - Creating an optimized production build...
12:56:36.822  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
12:56:36.822  	This information is used to shape Next.js' roadmap and prioritize features.
12:56:36.822  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
12:56:36.822  	https://nextjs.org/telemetry
12:56:41.964  	warn - You have enabled experimental features: extendedFontSizeScale, extendedSpacingScale
12:56:41.964  	warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.
12:56:52.660  	info  - Compiled successfully
12:56:52.660  	info  - Collecting page data...
12:56:53.952  	info  - Generating static pages (0/10)
12:56:55.127  	Unhandled error during request: Error: Failed to fetch API
12:56:55.127  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog.js:5738:11)
12:56:55.127  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:55.127  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog.js:3868:16)
12:56:55.127  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:55.127  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog.js:2711:22)
12:56:55.127  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:55.127  	Error occurred prerendering page "/blog". Read more: https://err.sh/next.js/prerender-error
12:56:55.127  	Error: Failed to fetch API
12:56:55.127  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog.js:5738:11)
12:56:55.127  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:55.127  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog.js:3868:16)
12:56:55.127  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:55.127  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog.js:2711:22)
12:56:55.127  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:55.128  	info  - Generating static pages (1/10)
12:56:55.158  	info  - Generating static pages (2/10)
12:56:55.188  	info  - Generating static pages (3/10)
12:56:55.741  	info  - Generating static pages (4/10)
12:56:55.792  	Unhandled error during request: Error: Failed to fetch API
12:56:55.792  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5682:11)
12:56:55.792  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:55.792  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:2275:16)
12:56:55.792  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:55.792  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5562:22)
12:56:55.792  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:55.792  	Error occurred prerendering page "/blog-category/main-category". Read more: https://err.sh/next.js/prerender-error
12:56:55.792  	Error: Failed to fetch API
12:56:55.792  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5682:11)
12:56:55.792  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:55.792  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:2275:16)
12:56:55.792  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:55.793  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5562:22)
12:56:55.793  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:55.793  	info  - Generating static pages (5/10)
12:56:55.828  	info  - Generating static pages (6/10)
12:56:56.260  	Unhandled error during request: Error: Failed to fetch API
12:56:56.260  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5682:11)
12:56:56.261  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.261  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:2275:16)
12:56:56.261  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.261  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5562:22)
12:56:56.261  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.261  	Error occurred prerendering page "/blog-category/subcategory". Read more: https://err.sh/next.js/prerender-error
12:56:56.261  	Error: Failed to fetch API
12:56:56.261  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5682:11)
12:56:56.261  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.261  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:2275:16)
12:56:56.261  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.261  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5562:22)
12:56:56.261  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.261  	info  - Generating static pages (7/10)
12:56:56.380  	Unhandled error during request: Error: Failed to fetch API
12:56:56.380  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5682:11)
12:56:56.380  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.380  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:2275:16)
12:56:56.380  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.380  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5562:22)
12:56:56.380  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.380  	Error occurred prerendering page "/blog-category/uncategorized". Read more: https://err.sh/next.js/prerender-error
12:56:56.380  	Error: Failed to fetch API
12:56:56.380  	    at fetchData (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5682:11)
12:56:56.380  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.380  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:2275:16)
12:56:56.380  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.380  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/blog-category/[category].js:5562:22)
12:56:56.380  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.380  	info  - Generating static pages (8/10)
12:56:56.416  	Unhandled error during request: Error: Failed to fetch API
12:56:56.416  	    at fetchData (/vercel/3a408542/.next/serverless/pages/[page].js:5521:11)
12:56:56.416  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.416  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/[page].js:2287:16)
12:56:56.416  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.416  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/[page].js:3763:22)
12:56:56.416  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.416  	Error occurred prerendering page "/about". Read more: https://err.sh/next.js/prerender-error
12:56:56.416  	Error: Failed to fetch API
12:56:56.416  	    at fetchData (/vercel/3a408542/.next/serverless/pages/[page].js:5521:11)
12:56:56.416  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.416  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/[page].js:2287:16)
12:56:56.416  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.416  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/[page].js:3763:22)
12:56:56.416  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.416  	info  - Generating static pages (9/10)
12:56:56.791  	Unhandled error during request: Error: Failed to fetch API
12:56:56.791  	    at fetchData (/vercel/3a408542/.next/serverless/pages/[page].js:5521:11)
12:56:56.791  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.791  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/[page].js:2287:16)
12:56:56.791  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.791  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/[page].js:3763:22)
12:56:56.792  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.794  	Error occurred prerendering page "/contact". Read more: https://err.sh/next.js/prerender-error
12:56:56.794  	Error: Failed to fetch API
12:56:56.794  	    at fetchData (/vercel/3a408542/.next/serverless/pages/[page].js:5521:11)
12:56:56.794  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.794  	    at async getStaticProps (/vercel/3a408542/.next/serverless/pages/[page].js:2287:16)
12:56:56.794  	    at async renderToHTML (/vercel/3a408542/node_modules/next/dist/next-server/server/render.js:28:109)
12:56:56.794  	    at async renderReqToHTML (/vercel/3a408542/.next/serverless/pages/[page].js:3763:22)
12:56:56.794  	    at async Object.exportPage [as default] (/vercel/3a408542/node_modules/next/dist/export/worker.js:12:92)
12:56:56.794  	> Build error occurred
12:56:56.794  	Error: Export encountered errors on following paths:
12:56:56.794  		/about
12:56:56.794  		/blog
12:56:56.794  		/blog-category/main-category
12:56:56.795  		/blog-category/subcategory
12:56:56.795  		/blog-category/uncategorized
12:56:56.795  		/contact
12:56:56.795  	    at exportApp (/vercel/3a408542/node_modules/next/dist/export/index.js:24:1103)
12:56:56.795  	    at runMicrotasks (<anonymous>)
12:56:56.795  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:56:56.795  	    at async build (/vercel/3a408542/node_modules/next/dist/build/index.js:37:212)
12:56:56.795  	info  - Generating static pages (10/10)
12:56:56.814  	Error: Command "next build" exited with 1
12:57:03.697  	Done with "package.json"
```

**Comment by haroldangenent** [comment]
@sboerrigter Thanks! This seems like a vague error though, all requests to `headless-wordpress` seem to fail. Locally, this is not an issue. I've sent you an e-mail about it.

**Comment by luukdv** [comment]
Build seems to work again 👍 https://vercel.com/trendwerk/nextjs-starter/p8me3bc7w
